import { Box, ResponsiveContext, Text } from "grommet";
import { useContext, useEffect, useState } from "react";

import TeamBox from "../TeamBox";
import BoxScore from "./BoxScore";
import HittingCard from "./HittingCard";
import PitchingCard from "./PitchingCard";

const stats = {
  league: "MLB",
  away_team: {
    team_id: "seattle-mariners",
    abbreviation: "SEA",
    active: true,
    first_name: "Seattle",
    last_name: "Mariners",
    conference: "American",
    division: "West",
    site_name: "Safeco Field",
    city: "Seattle",
    state: "Washington",
    full_name: "Seattle Mariners",
  },
  home_team: {
    team_id: "los-angeles-angels",
    abbreviation: "LAA",
    active: true,
    first_name: "Los Angeles",
    last_name: "Angels",
    conference: "American",
    division: "West",
    site_name: "Angel Stadium of Anaheim",
    city: "Anaheim",
    state: "California",
    full_name: "Los Angeles Angels",
  },
  away_period_scores: [0, 0, 2, 1, 0, 0, 0, 0, 0],
  home_period_scores: [0, 2, 0, 0, 0, 0, 1, 0, 1],
  away_errors: 1,
  home_errors: 0,
  away_batters: [
    {
      last_name: "Ackley",
      first_name: "Dustin",
      display_name: "Dustin Ackley",
      position: "2B",
      bat_order: 1,
      sub_bat_order: 0,
      sacrifices: 0,
      at_bats: 4,
      plate_appearances: 4,
      singles: 0,
      doubles: 0,
      triples: 0,
      home_runs: 0,
      sac_flies: 0,
      sac_hits: 0,
      stolen_bases: 0,
      caught_stealing: 0,
      rbi_with_two_outs: 0,
      total_bases: 0,
      runs: 0,
      hits: 0,
      rbi: 0,
      walks: 0,
      strike_outs: 0,
      left_on_base: 3,
      hit_by_pitch: 0,
      team_abbreviation: "SEA",
      ops: 0.0,
      avg: 0.0,
      obp: 0.0,
      slg: 0.0,
      at_bats_per_home_run: 0.0,
      at_bats_per_rbi: 0.0,
      walk_rate: 0.0,
      plate_appearances_per_rbi: 0.0,
      plate_appearances_per_home_run: 0.0,
      extra_base_hits: 0,
      stolen_base_average: 0.0,
      strikeout_rate: 0.0,
      ops_string: ".000",
      slg_string: ".000",
      obp_string: ".000",
      avg_string: ".000",
      batting_highlights: "0-4",
    },
    {
      last_name: "Gutierrez",
      first_name: "Franklin",
      display_name: "Franklin Gutierrez",
      position: "CF",
      bat_order: 2,
      sub_bat_order: 0,
      sacrifices: 1,
      at_bats: 3,
      plate_appearances: 4,
      singles: 0,
      doubles: 0,
      triples: 0,
      home_runs: 0,
      sac_flies: 1,
      sac_hits: 0,
      stolen_bases: 0,
      caught_stealing: 0,
      rbi_with_two_outs: 0,
      total_bases: 0,
      runs: 0,
      hits: 0,
      rbi: 1,
      walks: 0,
      strike_outs: 1,
      left_on_base: 1,
      hit_by_pitch: 0,
      team_abbreviation: "SEA",
      ops: 0.0,
      avg: 0.0,
      obp: 0.0,
      slg: 0.0,
      at_bats_per_home_run: 0.0,
      at_bats_per_rbi: 3.0,
      walk_rate: 0.0,
      plate_appearances_per_rbi: 4.0,
      plate_appearances_per_home_run: 0.0,
      extra_base_hits: 0,
      stolen_base_average: 0.0,
      strikeout_rate: 0.333,
      ops_string: ".000",
      slg_string: ".000",
      obp_string: ".000",
      avg_string: ".000",
      batting_highlights: "0-3, RBI",
    },
    {
      last_name: "Seager",
      first_name: "Kyle",
      display_name: "Kyle Seager",
      position: "3B",
      bat_order: 3,
      sub_bat_order: 0,
      sacrifices: 0,
      at_bats: 3,
      plate_appearances: 4,
      singles: 0,
      doubles: 0,
      triples: 0,
      home_runs: 0,
      sac_flies: 0,
      sac_hits: 0,
      stolen_bases: 0,
      caught_stealing: 0,
      rbi_with_two_outs: 0,
      total_bases: 0,
      runs: 0,
      hits: 0,
      rbi: 0,
      walks: 1,
      strike_outs: 1,
      left_on_base: 2,
      hit_by_pitch: 0,
      team_abbreviation: "SEA",
      ops: 0.25,
      avg: 0.0,
      obp: 0.25,
      slg: 0.0,
      at_bats_per_home_run: 0.0,
      at_bats_per_rbi: 0.0,
      walk_rate: 0.25,
      plate_appearances_per_rbi: 0.0,
      plate_appearances_per_home_run: 0.0,
      extra_base_hits: 0,
      stolen_base_average: 0.0,
      strikeout_rate: 0.333,
      ops_string: ".250",
      slg_string: ".000",
      obp_string: ".250",
      avg_string: ".000",
      batting_highlights: "0-3",
    },
    {
      last_name: "Montero",
      first_name: "Jesús",
      display_name: "Jesús Montero",
      position: "DH",
      bat_order: 4,
      sub_bat_order: 0,
      sacrifices: 0,
      at_bats: 4,
      plate_appearances: 4,
      singles: 1,
      doubles: 0,
      triples: 0,
      home_runs: 0,
      sac_flies: 0,
      sac_hits: 0,
      stolen_bases: 0,
      caught_stealing: 0,
      rbi_with_two_outs: 0,
      total_bases: 1,
      runs: 0,
      hits: 1,
      rbi: 0,
      walks: 0,
      strike_outs: 1,
      left_on_base: 1,
      hit_by_pitch: 0,
      team_abbreviation: "SEA",
      ops: 0.5,
      avg: 0.25,
      obp: 0.25,
      slg: 0.25,
      at_bats_per_home_run: 0.0,
      at_bats_per_rbi: 0.0,
      walk_rate: 0.0,
      plate_appearances_per_rbi: 0.0,
      plate_appearances_per_home_run: 0.0,
      extra_base_hits: 0,
      stolen_base_average: 0.0,
      strikeout_rate: 0.25,
      ops_string: ".500",
      slg_string: ".250",
      obp_string: ".250",
      avg_string: ".250",
      batting_highlights: "1-4",
    },
    {
      last_name: "Smoak",
      first_name: "Justin",
      display_name: "Justin Smoak",
      position: "1B",
      bat_order: 5,
      sub_bat_order: 0,
      sacrifices: 0,
      at_bats: 4,
      plate_appearances: 4,
      singles: 0,
      doubles: 0,
      triples: 0,
      home_runs: 1,
      sac_flies: 0,
      sac_hits: 0,
      stolen_bases: 0,
      caught_stealing: 0,
      rbi_with_two_outs: 0,
      total_bases: 4,
      runs: 1,
      hits: 1,
      rbi: 1,
      walks: 0,
      strike_outs: 0,
      left_on_base: 1,
      hit_by_pitch: 0,
      team_abbreviation: "SEA",
      ops: 1.25,
      avg: 0.25,
      obp: 0.25,
      slg: 1.0,
      at_bats_per_home_run: 4.0,
      at_bats_per_rbi: 4.0,
      walk_rate: 0.0,
      plate_appearances_per_rbi: 4.0,
      plate_appearances_per_home_run: 4.0,
      extra_base_hits: 1,
      stolen_base_average: 0.0,
      strikeout_rate: 0.0,
      ops_string: "1.250",
      slg_string: "1.000",
      obp_string: ".250",
      avg_string: ".250",
      batting_highlights: "1-4, HR, R, RBI",
    },
    {
      last_name: "Olivo",
      first_name: "Miguel",
      display_name: "Miguel Olivo",
      position: "C",
      bat_order: 6,
      sub_bat_order: 0,
      sacrifices: 0,
      at_bats: 4,
      plate_appearances: 4,
      singles: 1,
      doubles: 0,
      triples: 0,
      home_runs: 0,
      sac_flies: 0,
      sac_hits: 0,
      stolen_bases: 0,
      caught_stealing: 1,
      rbi_with_two_outs: 0,
      total_bases: 1,
      runs: 0,
      hits: 1,
      rbi: 0,
      walks: 0,
      strike_outs: 1,
      left_on_base: 1,
      hit_by_pitch: 0,
      team_abbreviation: "SEA",
      ops: 0.5,
      avg: 0.25,
      obp: 0.25,
      slg: 0.25,
      at_bats_per_home_run: 0.0,
      at_bats_per_rbi: 0.0,
      walk_rate: 0.0,
      plate_appearances_per_rbi: 0.0,
      plate_appearances_per_home_run: 0.0,
      extra_base_hits: 0,
      stolen_base_average: 0.0,
      strikeout_rate: 0.25,
      ops_string: ".500",
      slg_string: ".250",
      obp_string: ".250",
      avg_string: ".250",
      batting_highlights: "1-4",
    },
    {
      last_name: "Wells",
      first_name: "Casper",
      display_name: "Casper Wells",
      position: "RF",
      bat_order: 7,
      sub_bat_order: 0,
      sacrifices: 0,
      at_bats: 2,
      plate_appearances: 4,
      singles: 0,
      doubles: 0,
      triples: 0,
      home_runs: 0,
      sac_flies: 0,
      sac_hits: 0,
      stolen_bases: 0,
      caught_stealing: 0,
      rbi_with_two_outs: 0,
      total_bases: 0,
      runs: 1,
      hits: 0,
      rbi: 0,
      walks: 2,
      strike_outs: 0,
      left_on_base: 0,
      hit_by_pitch: 0,
      team_abbreviation: "SEA",
      ops: 0.5,
      avg: 0.0,
      obp: 0.5,
      slg: 0.0,
      at_bats_per_home_run: 0.0,
      at_bats_per_rbi: 0.0,
      walk_rate: 0.5,
      plate_appearances_per_rbi: 0.0,
      plate_appearances_per_home_run: 0.0,
      extra_base_hits: 0,
      stolen_base_average: 0.0,
      strikeout_rate: 0.0,
      ops_string: ".500",
      slg_string: ".000",
      obp_string: ".500",
      avg_string: ".000",
      batting_highlights: "0-2, R",
    },
    {
      last_name: "Figgins",
      first_name: "Desmond",
      display_name: "Chone Figgins",
      position: "LF",
      bat_order: 8,
      sub_bat_order: 0,
      sacrifices: 0,
      at_bats: 2,
      plate_appearances: 3,
      singles: 0,
      doubles: 0,
      triples: 0,
      home_runs: 0,
      sac_flies: 0,
      sac_hits: 0,
      stolen_bases: 0,
      caught_stealing: 0,
      rbi_with_two_outs: 0,
      total_bases: 0,
      runs: 1,
      hits: 0,
      rbi: 0,
      walks: 1,
      strike_outs: 2,
      left_on_base: 1,
      hit_by_pitch: 0,
      team_abbreviation: "SEA",
      ops: 0.333,
      avg: 0.0,
      obp: 0.333,
      slg: 0.0,
      at_bats_per_home_run: 0.0,
      at_bats_per_rbi: 0.0,
      walk_rate: 0.333,
      plate_appearances_per_rbi: 0.0,
      plate_appearances_per_home_run: 0.0,
      extra_base_hits: 0,
      stolen_base_average: 0.0,
      strikeout_rate: 1.0,
      ops_string: ".333",
      slg_string: ".000",
      obp_string: ".333",
      avg_string: ".000",
      batting_highlights: "0-2, R",
    },
    {
      last_name: "Ryan",
      first_name: "Brendan",
      display_name: "Brendan Ryan",
      position: "SS",
      bat_order: 9,
      sub_bat_order: 0,
      sacrifices: 0,
      at_bats: 3,
      plate_appearances: 3,
      singles: 1,
      doubles: 1,
      triples: 0,
      home_runs: 0,
      sac_flies: 0,
      sac_hits: 0,
      stolen_bases: 0,
      caught_stealing: 0,
      rbi_with_two_outs: 0,
      total_bases: 3,
      runs: 0,
      hits: 2,
      rbi: 1,
      walks: 0,
      strike_outs: 0,
      left_on_base: 0,
      hit_by_pitch: 0,
      team_abbreviation: "SEA",
      ops: 1.667,
      avg: 0.667,
      obp: 0.667,
      slg: 1.0,
      at_bats_per_home_run: 0.0,
      at_bats_per_rbi: 3.0,
      walk_rate: 0.0,
      plate_appearances_per_rbi: 3.0,
      plate_appearances_per_home_run: 0.0,
      extra_base_hits: 1,
      stolen_base_average: 0.0,
      strikeout_rate: 0.0,
      ops_string: "1.667",
      slg_string: "1.000",
      obp_string: ".667",
      avg_string: ".667",
      batting_highlights: "2-3, RBI, 2B",
    },
  ],
  home_batters: [
    {
      last_name: "Trout",
      first_name: "Michael",
      display_name: "Mike Trout",
      position: "CF-LF",
      bat_order: 1,
      sub_bat_order: 0,
      sacrifices: 0,
      at_bats: 3,
      plate_appearances: 5,
      singles: 0,
      doubles: 0,
      triples: 0,
      home_runs: 0,
      sac_flies: 0,
      sac_hits: 0,
      stolen_bases: 0,
      caught_stealing: 0,
      rbi_with_two_outs: 0,
      total_bases: 0,
      runs: 0,
      hits: 0,
      rbi: 0,
      walks: 2,
      strike_outs: 0,
      left_on_base: 2,
      hit_by_pitch: 0,
      team_abbreviation: "LAA",
      ops: 0.4,
      avg: 0.0,
      obp: 0.4,
      slg: 0.0,
      at_bats_per_home_run: 0.0,
      at_bats_per_rbi: 0.0,
      walk_rate: 0.4,
      plate_appearances_per_rbi: 0.0,
      plate_appearances_per_home_run: 0.0,
      extra_base_hits: 0,
      stolen_base_average: 0.0,
      strikeout_rate: 0.0,
      ops_string: ".400",
      slg_string: ".000",
      obp_string: ".400",
      avg_string: ".000",
      batting_highlights: "0-3",
    },
    {
      last_name: "Hunter",
      first_name: "Torii",
      display_name: "Torii Hunter",
      position: "RF",
      bat_order: 2,
      sub_bat_order: 0,
      sacrifices: 0,
      at_bats: 5,
      plate_appearances: 5,
      singles: 2,
      doubles: 0,
      triples: 0,
      home_runs: 0,
      sac_flies: 0,
      sac_hits: 0,
      stolen_bases: 0,
      caught_stealing: 0,
      rbi_with_two_outs: 1,
      total_bases: 2,
      runs: 0,
      hits: 2,
      rbi: 2,
      walks: 0,
      strike_outs: 2,
      left_on_base: 3,
      hit_by_pitch: 0,
      team_abbreviation: "LAA",
      ops: 0.8,
      avg: 0.4,
      obp: 0.4,
      slg: 0.4,
      at_bats_per_home_run: 0.0,
      at_bats_per_rbi: 2.5,
      walk_rate: 0.0,
      plate_appearances_per_rbi: 2.5,
      plate_appearances_per_home_run: 0.0,
      extra_base_hits: 0,
      stolen_base_average: 0.0,
      strikeout_rate: 0.4,
      ops_string: ".800",
      slg_string: ".400",
      obp_string: ".400",
      avg_string: ".400",
      batting_highlights: "2-5, 2 RBI",
    },
    {
      last_name: "Pujols",
      first_name: "Jose",
      display_name: "Albert Pujols",
      position: "DH",
      bat_order: 3,
      sub_bat_order: 0,
      sacrifices: 0,
      at_bats: 4,
      plate_appearances: 4,
      singles: 1,
      doubles: 0,
      triples: 0,
      home_runs: 0,
      sac_flies: 0,
      sac_hits: 0,
      stolen_bases: 0,
      caught_stealing: 0,
      rbi_with_two_outs: 0,
      total_bases: 1,
      runs: 0,
      hits: 1,
      rbi: 0,
      walks: 0,
      strike_outs: 3,
      left_on_base: 0,
      hit_by_pitch: 0,
      team_abbreviation: "LAA",
      ops: 0.5,
      avg: 0.25,
      obp: 0.25,
      slg: 0.25,
      at_bats_per_home_run: 0.0,
      at_bats_per_rbi: 0.0,
      walk_rate: 0.0,
      plate_appearances_per_rbi: 0.0,
      plate_appearances_per_home_run: 0.0,
      extra_base_hits: 0,
      stolen_base_average: 0.0,
      strikeout_rate: 0.75,
      ops_string: ".500",
      slg_string: ".250",
      obp_string: ".250",
      avg_string: ".250",
      batting_highlights: "1-4",
    },
    {
      last_name: "Morales",
      first_name: "Kendrys",
      display_name: "Kendrys Morales",
      position: "1B",
      bat_order: 4,
      sub_bat_order: 0,
      sacrifices: 0,
      at_bats: 4,
      plate_appearances: 4,
      singles: 1,
      doubles: 0,
      triples: 0,
      home_runs: 0,
      sac_flies: 0,
      sac_hits: 0,
      stolen_bases: 0,
      caught_stealing: 0,
      rbi_with_two_outs: 0,
      total_bases: 1,
      runs: 1,
      hits: 1,
      rbi: 0,
      walks: 0,
      strike_outs: 0,
      left_on_base: 2,
      hit_by_pitch: 0,
      team_abbreviation: "LAA",
      ops: 0.5,
      avg: 0.25,
      obp: 0.25,
      slg: 0.25,
      at_bats_per_home_run: 0.0,
      at_bats_per_rbi: 0.0,
      walk_rate: 0.0,
      plate_appearances_per_rbi: 0.0,
      plate_appearances_per_home_run: 0.0,
      extra_base_hits: 0,
      stolen_base_average: 0.0,
      strikeout_rate: 0.0,
      ops_string: ".500",
      slg_string: ".250",
      obp_string: ".250",
      avg_string: ".250",
      batting_highlights: "1-4, R",
    },
    {
      last_name: "Callaspo",
      first_name: "Alberto",
      display_name: "Alberto Callaspo",
      position: "3B",
      bat_order: 5,
      sub_bat_order: 0,
      sacrifices: 0,
      at_bats: 4,
      plate_appearances: 4,
      singles: 2,
      doubles: 0,
      triples: 0,
      home_runs: 0,
      sac_flies: 0,
      sac_hits: 0,
      stolen_bases: 0,
      caught_stealing: 0,
      rbi_with_two_outs: 0,
      total_bases: 2,
      runs: 1,
      hits: 2,
      rbi: 0,
      walks: 0,
      strike_outs: 0,
      left_on_base: 0,
      hit_by_pitch: 0,
      team_abbreviation: "LAA",
      ops: 1.0,
      avg: 0.5,
      obp: 0.5,
      slg: 0.5,
      at_bats_per_home_run: 0.0,
      at_bats_per_rbi: 0.0,
      walk_rate: 0.0,
      plate_appearances_per_rbi: 0.0,
      plate_appearances_per_home_run: 0.0,
      extra_base_hits: 0,
      stolen_base_average: 0.0,
      strikeout_rate: 0.0,
      ops_string: "1.000",
      slg_string: ".500",
      obp_string: ".500",
      avg_string: ".500",
      batting_highlights: "2-4, R",
    },
    {
      last_name: "Kendrick",
      first_name: "Howard",
      display_name: "Howie Kendrick",
      position: "2B",
      bat_order: 6,
      sub_bat_order: 0,
      sacrifices: 1,
      at_bats: 3,
      plate_appearances: 4,
      singles: 0,
      doubles: 0,
      triples: 0,
      home_runs: 0,
      sac_flies: 0,
      sac_hits: 1,
      stolen_bases: 0,
      caught_stealing: 0,
      rbi_with_two_outs: 0,
      total_bases: 0,
      runs: 0,
      hits: 0,
      rbi: 0,
      walks: 0,
      strike_outs: 1,
      left_on_base: 1,
      hit_by_pitch: 0,
      team_abbreviation: "LAA",
      ops: 0.0,
      avg: 0.0,
      obp: 0.0,
      slg: 0.0,
      at_bats_per_home_run: 0.0,
      at_bats_per_rbi: 0.0,
      walk_rate: 0.0,
      plate_appearances_per_rbi: 0.0,
      plate_appearances_per_home_run: 0.0,
      extra_base_hits: 0,
      stolen_base_average: 0.0,
      strikeout_rate: 0.333,
      ops_string: ".000",
      slg_string: ".000",
      obp_string: ".000",
      avg_string: ".000",
      batting_highlights: "0-3",
    },
    {
      last_name: "Aybar",
      first_name: "Erick",
      display_name: "Erick Aybar",
      position: "SS",
      bat_order: 7,
      sub_bat_order: 0,
      sacrifices: 0,
      at_bats: 4,
      plate_appearances: 4,
      singles: 1,
      doubles: 1,
      triples: 0,
      home_runs: 0,
      sac_flies: 0,
      sac_hits: 0,
      stolen_bases: 1,
      caught_stealing: 0,
      rbi_with_two_outs: 0,
      total_bases: 3,
      runs: 0,
      hits: 2,
      rbi: 2,
      walks: 0,
      strike_outs: 0,
      left_on_base: 0,
      hit_by_pitch: 0,
      team_abbreviation: "LAA",
      ops: 1.25,
      avg: 0.5,
      obp: 0.5,
      slg: 0.75,
      at_bats_per_home_run: 0.0,
      at_bats_per_rbi: 2.0,
      walk_rate: 0.0,
      plate_appearances_per_rbi: 2.0,
      plate_appearances_per_home_run: 0.0,
      extra_base_hits: 1,
      stolen_base_average: 1.0,
      strikeout_rate: 0.0,
      ops_string: "1.250",
      slg_string: ".750",
      obp_string: ".500",
      avg_string: ".500",
      batting_highlights: "2-4, 2 RBI, 2B, SB",
    },
    {
      last_name: "Trumbo",
      first_name: "Mark",
      display_name: "Mark Trumbo",
      position: "LF",
      bat_order: 8,
      sub_bat_order: 0,
      sacrifices: 0,
      at_bats: 3,
      plate_appearances: 3,
      singles: 0,
      doubles: 0,
      triples: 0,
      home_runs: 0,
      sac_flies: 0,
      sac_hits: 0,
      stolen_bases: 0,
      caught_stealing: 0,
      rbi_with_two_outs: 0,
      total_bases: 0,
      runs: 0,
      hits: 0,
      rbi: 0,
      walks: 0,
      strike_outs: 2,
      left_on_base: 2,
      hit_by_pitch: 0,
      team_abbreviation: "LAA",
      ops: 0.0,
      avg: 0.0,
      obp: 0.0,
      slg: 0.0,
      at_bats_per_home_run: 0.0,
      at_bats_per_rbi: 0.0,
      walk_rate: 0.0,
      plate_appearances_per_rbi: 0.0,
      plate_appearances_per_home_run: 0.0,
      extra_base_hits: 0,
      stolen_base_average: 0.0,
      strikeout_rate: 0.667,
      ops_string: ".000",
      slg_string: ".000",
      obp_string: ".000",
      avg_string: ".000",
      batting_highlights: "0-3",
    },
    {
      last_name: "Wilson",
      first_name: "Robert",
      display_name: "Bobby Wilson",
      position: "C",
      bat_order: 8,
      sub_bat_order: 1,
      sacrifices: 0,
      at_bats: 0,
      plate_appearances: 0,
      singles: 0,
      doubles: 0,
      triples: 0,
      home_runs: 0,
      sac_flies: 0,
      sac_hits: 0,
      stolen_bases: 0,
      caught_stealing: 0,
      rbi_with_two_outs: 0,
      total_bases: 0,
      runs: 0,
      hits: 0,
      rbi: 0,
      walks: 0,
      strike_outs: 0,
      left_on_base: 0,
      hit_by_pitch: 0,
      team_abbreviation: "LAA",
      ops: 0.0,
      avg: 0.0,
      obp: 0.0,
      slg: 0.0,
      at_bats_per_home_run: 0.0,
      at_bats_per_rbi: 0.0,
      walk_rate: 0.0,
      plate_appearances_per_rbi: 0.0,
      plate_appearances_per_home_run: 0.0,
      extra_base_hits: 0,
      stolen_base_average: 0.0,
      strikeout_rate: 0.0,
      ops_string: ".000",
      slg_string: ".000",
      obp_string: ".000",
      avg_string: ".000",
      batting_highlights: "0-0",
    },
    {
      last_name: "Izturis",
      first_name: "Maicer",
      display_name: "Maicer Izturis",
      position: "PH",
      bat_order: 8,
      sub_bat_order: 2,
      sacrifices: 0,
      at_bats: 1,
      plate_appearances: 1,
      singles: 1,
      doubles: 0,
      triples: 0,
      home_runs: 0,
      sac_flies: 0,
      sac_hits: 0,
      stolen_bases: 0,
      caught_stealing: 0,
      rbi_with_two_outs: 0,
      total_bases: 1,
      runs: 1,
      hits: 1,
      rbi: 0,
      walks: 0,
      strike_outs: 0,
      left_on_base: 0,
      hit_by_pitch: 0,
      team_abbreviation: "LAA",
      ops: 2.0,
      avg: 1.0,
      obp: 1.0,
      slg: 1.0,
      at_bats_per_home_run: 0.0,
      at_bats_per_rbi: 0.0,
      walk_rate: 0.0,
      plate_appearances_per_rbi: 0.0,
      plate_appearances_per_home_run: 0.0,
      extra_base_hits: 0,
      stolen_base_average: 0.0,
      strikeout_rate: 0.0,
      ops_string: "2.000",
      slg_string: "1.000",
      obp_string: "1.000",
      avg_string: "1.000",
      batting_highlights: "1-1, R",
    },
    {
      last_name: "Iannetta",
      first_name: "Christopher",
      display_name: "Chris Iannetta",
      position: "C",
      bat_order: 9,
      sub_bat_order: 0,
      sacrifices: 0,
      at_bats: 2,
      plate_appearances: 3,
      singles: 1,
      doubles: 0,
      triples: 0,
      home_runs: 0,
      sac_flies: 0,
      sac_hits: 0,
      stolen_bases: 0,
      caught_stealing: 0,
      rbi_with_two_outs: 0,
      total_bases: 1,
      runs: 0,
      hits: 1,
      rbi: 0,
      walks: 1,
      strike_outs: 1,
      left_on_base: 1,
      hit_by_pitch: 0,
      team_abbreviation: "LAA",
      ops: 1.167,
      avg: 0.5,
      obp: 0.667,
      slg: 0.5,
      at_bats_per_home_run: 0.0,
      at_bats_per_rbi: 0.0,
      walk_rate: 0.333,
      plate_appearances_per_rbi: 0.0,
      plate_appearances_per_home_run: 0.0,
      extra_base_hits: 0,
      stolen_base_average: 0.0,
      strikeout_rate: 0.5,
      ops_string: "1.167",
      slg_string: ".500",
      obp_string: ".667",
      avg_string: ".500",
      batting_highlights: "1-2",
    },
    {
      last_name: "Bourjos",
      first_name: "Peter",
      display_name: "Peter Bourjos",
      position: "PR-CF",
      bat_order: 9,
      sub_bat_order: 1,
      sacrifices: 1,
      at_bats: 0,
      plate_appearances: 1,
      singles: 0,
      doubles: 0,
      triples: 0,
      home_runs: 0,
      sac_flies: 0,
      sac_hits: 1,
      stolen_bases: 0,
      caught_stealing: 0,
      rbi_with_two_outs: 0,
      total_bases: 0,
      runs: 1,
      hits: 0,
      rbi: 0,
      walks: 0,
      strike_outs: 0,
      left_on_base: 0,
      hit_by_pitch: 0,
      team_abbreviation: "LAA",
      ops: 0.0,
      avg: 0.0,
      obp: 0.0,
      slg: 0.0,
      at_bats_per_home_run: 0.0,
      at_bats_per_rbi: 0.0,
      walk_rate: 0.0,
      plate_appearances_per_rbi: 0.0,
      plate_appearances_per_home_run: 0.0,
      extra_base_hits: 0,
      stolen_base_average: 0.0,
      strikeout_rate: 0.0,
      ops_string: ".000",
      slg_string: ".000",
      obp_string: ".000",
      avg_string: ".000",
      batting_highlights: "0-0, R",
    },
  ],
  away_pitchers: [
    {
      last_name: "Hernández",
      first_name: "Félix",
      display_name: "Félix Hernández",
      pitch_order: 1,
      win: false,
      loss: false,
      save: false,
      hold: false,
      era: 3.0,
      whip: 1.17,
      innings_pitched: 6.0,
      hits_allowed: 5,
      runs_allowed: 2,
      earned_runs: 2,
      walks: 2,
      intentional_walks: 0,
      strike_outs: 9,
      home_runs_allowed: 0,
      pitch_count: 103,
      pitches_strikes: 71,
      wild_pitches: 1,
      hit_by_pitch: 0,
      errors: 0,
      team_abbreviation: "SEA",
    },
    {
      last_name: "Kinney",
      first_name: "Joshua",
      display_name: "Josh Kinney",
      pitch_order: 2,
      win: false,
      loss: false,
      save: false,
      hold: false,
      era: 13.5,
      whip: 4.5,
      innings_pitched: 0.2,
      hits_allowed: 3,
      runs_allowed: 1,
      earned_runs: 1,
      walks: 0,
      intentional_walks: 0,
      strike_outs: 0,
      home_runs_allowed: 0,
      pitch_count: 20,
      pitches_strikes: 16,
      wild_pitches: 0,
      hit_by_pitch: 0,
      errors: 0,
      team_abbreviation: "SEA",
    },
    {
      last_name: "Pérez",
      first_name: "Óliver",
      display_name: "Óliver Pérez",
      pitch_order: 3,
      win: false,
      loss: false,
      save: false,
      hold: false,
      era: 0.0,
      whip: 0.0,
      innings_pitched: 0.1,
      hits_allowed: 0,
      runs_allowed: 0,
      earned_runs: 0,
      walks: 0,
      intentional_walks: 0,
      strike_outs: 0,
      home_runs_allowed: 0,
      pitch_count: 6,
      pitches_strikes: 4,
      wild_pitches: 0,
      hit_by_pitch: 0,
      errors: 0,
      team_abbreviation: "SEA",
    },
    {
      last_name: "Pryor",
      first_name: "Stephen",
      display_name: "Stephen Pryor",
      pitch_order: 4,
      win: false,
      loss: true,
      save: false,
      hold: false,
      era: 6.75,
      whip: 2.25,
      innings_pitched: 1.1,
      hits_allowed: 2,
      runs_allowed: 1,
      earned_runs: 1,
      walks: 1,
      intentional_walks: 1,
      strike_outs: 0,
      home_runs_allowed: 0,
      pitch_count: 27,
      pitches_strikes: 15,
      wild_pitches: 1,
      hit_by_pitch: 0,
      errors: 0,
      team_abbreviation: "SEA",
    },
  ],
  home_pitchers: [
    {
      last_name: "Wilson",
      first_name: "Christopher",
      display_name: "C.J. Wilson",
      pitch_order: 1,
      win: false,
      loss: false,
      save: false,
      hold: false,
      era: 5.06,
      whip: 1.5,
      innings_pitched: 5.1,
      hits_allowed: 5,
      runs_allowed: 3,
      earned_runs: 3,
      walks: 3,
      intentional_walks: 0,
      strike_outs: 5,
      home_runs_allowed: 1,
      pitch_count: 87,
      pitches_strikes: 56,
      wild_pitches: 0,
      hit_by_pitch: 0,
      errors: 0,
      team_abbreviation: "LAA",
    },
    {
      last_name: "Williams",
      first_name: "Jerome",
      display_name: "Jerome Williams",
      pitch_order: 2,
      win: false,
      loss: false,
      save: false,
      hold: false,
      era: 0.0,
      whip: 0.0,
      innings_pitched: 1.2,
      hits_allowed: 0,
      runs_allowed: 0,
      earned_runs: 0,
      walks: 0,
      intentional_walks: 0,
      strike_outs: 1,
      home_runs_allowed: 0,
      pitch_count: 12,
      pitches_strikes: 8,
      wild_pitches: 0,
      hit_by_pitch: 0,
      errors: 0,
      team_abbreviation: "LAA",
    },
    {
      last_name: "Jepsen",
      first_name: "Kevin",
      display_name: "Kevin Jepsen",
      pitch_order: 3,
      win: false,
      loss: false,
      save: false,
      hold: false,
      era: 0.0,
      whip: 1.0,
      innings_pitched: 1.0,
      hits_allowed: 0,
      runs_allowed: 0,
      earned_runs: 0,
      walks: 1,
      intentional_walks: 0,
      strike_outs: 0,
      home_runs_allowed: 0,
      pitch_count: 14,
      pitches_strikes: 6,
      wild_pitches: 0,
      hit_by_pitch: 0,
      errors: 0,
      team_abbreviation: "LAA",
    },
    {
      last_name: "Frieri",
      first_name: "Ernesto",
      display_name: "Ernesto Frieri",
      pitch_order: 4,
      win: true,
      loss: false,
      save: false,
      hold: false,
      era: 0.0,
      whip: 0.0,
      innings_pitched: 1.0,
      hits_allowed: 0,
      runs_allowed: 0,
      earned_runs: 0,
      walks: 0,
      intentional_walks: 0,
      strike_outs: 0,
      home_runs_allowed: 0,
      pitch_count: 5,
      pitches_strikes: 3,
      wild_pitches: 0,
      hit_by_pitch: 0,
      errors: 0,
      team_abbreviation: "LAA",
    },
  ],
  away_fielding: [
    {
      last_name: "Olivo",
      first_name: "Miguel",
      display_name: "Miguel Olivo",
      errors: 1,
      team_abbreviation: "SEA",
    },
    {
      last_name: "Gutierrez",
      first_name: "Franklin",
      display_name: "Franklin Gutierrez",
      errors: 0,
      team_abbreviation: "SEA",
    },
    {
      last_name: "Smoak",
      first_name: "Justin",
      display_name: "Justin Smoak",
      errors: 0,
      team_abbreviation: "SEA",
    },
    {
      last_name: "Wells",
      first_name: "Casper",
      display_name: "Casper Wells",
      errors: 0,
      team_abbreviation: "SEA",
    },
    {
      last_name: "Seager",
      first_name: "Kyle",
      display_name: "Kyle Seager",
      errors: 0,
      team_abbreviation: "SEA",
    },
    {
      last_name: "Montero",
      first_name: "Jesús",
      display_name: "Jesús Montero",
      errors: 0,
      team_abbreviation: "SEA",
    },
    {
      last_name: "Ackley",
      first_name: "Dustin",
      display_name: "Dustin Ackley",
      errors: 0,
      team_abbreviation: "SEA",
    },
    {
      last_name: "Figgins",
      first_name: "Desmond",
      display_name: "Chone Figgins",
      errors: 0,
      team_abbreviation: "SEA",
    },
    {
      last_name: "Ryan",
      first_name: "Brendan",
      display_name: "Brendan Ryan",
      errors: 0,
      team_abbreviation: "SEA",
    },
  ],
  home_fielding: [
    {
      last_name: "Trumbo",
      first_name: "Mark",
      display_name: "Mark Trumbo",
      errors: 0,
      team_abbreviation: "LAA",
    },
    {
      last_name: "Aybar",
      first_name: "Erick",
      display_name: "Erick Aybar",
      errors: 0,
      team_abbreviation: "LAA",
    },
    {
      last_name: "Kendrick",
      first_name: "Howard",
      display_name: "Howie Kendrick",
      errors: 0,
      team_abbreviation: "LAA",
    },
    {
      last_name: "Trout",
      first_name: "Michael",
      display_name: "Mike Trout",
      errors: 0,
      team_abbreviation: "LAA",
    },
    {
      last_name: "Pujols",
      first_name: "Jose",
      display_name: "Albert Pujols",
      errors: 0,
      team_abbreviation: "LAA",
    },
    {
      last_name: "Iannetta",
      first_name: "Christopher",
      display_name: "Chris Iannetta",
      errors: 0,
      team_abbreviation: "LAA",
    },
    {
      last_name: "Morales",
      first_name: "Kendrys",
      display_name: "Kendrys Morales",
      errors: 0,
      team_abbreviation: "LAA",
    },
    {
      last_name: "Bourjos",
      first_name: "Peter",
      display_name: "Peter Bourjos",
      errors: 0,
      team_abbreviation: "LAA",
    },
    {
      last_name: "Wilson",
      first_name: "Robert",
      display_name: "Bobby Wilson",
      errors: 0,
      team_abbreviation: "LAA",
    },
    {
      last_name: "Hunter",
      first_name: "Torii",
      display_name: "Torii Hunter",
      errors: 0,
      team_abbreviation: "LAA",
    },
    {
      last_name: "Callaspo",
      first_name: "Alberto",
      display_name: "Alberto Callaspo",
      errors: 0,
      team_abbreviation: "LAA",
    },
    {
      last_name: "Izturis",
      first_name: "Maicer",
      display_name: "Maicer Izturis",
      errors: 0,
      team_abbreviation: "LAA",
    },
  ],
  officials: [
    {
      position: "Home Plate",
      first_name: "Gary",
      last_name: "Cederstrom",
    },
    {
      position: "First Base",
      first_name: "Lance",
      last_name: "Barksdale",
    },
    {
      position: "Second Base",
      first_name: "Fieldin",
      last_name: "Culbreth",
    },
    {
      position: "Third Base",
      first_name: "Adrian",
      last_name: "Johnson",
    },
  ],
  event_information: {
    temperature: 71,
    site: {
      capacity: 45050,
      surface: "Grass",
      name: "Angel Stadium of Anaheim",
      state: "California",
      city: "Anaheim",
    },
    attendance: 37916,
    duration: "3:03",
    status: "completed",
    season_type: "regular",
    start_date_time: "2012-09-26T19:05:00-07:00",
  },
  away_batter_totals: {
    sacrifices: 1,
    at_bats: 29,
    plate_appearances: 34,
    singles: 3,
    doubles: 1,
    triples: 0,
    home_runs: 1,
    sac_flies: 1,
    sac_hits: 0,
    stolen_bases: 0,
    caught_stealing: 1,
    rbi_with_two_outs: 0,
    total_bases: 9,
    runs: 3,
    hits: 5,
    rbi: 3,
    walks: 4,
    strike_outs: 6,
    left_on_base: 10,
    hit_by_pitch: 0,
    ops: 0.575,
    avg: 0.172,
    obp: 0.265,
    slg: 0.31,
    at_bats_per_home_run: 29.0,
    at_bats_per_rbi: 9.667,
    walk_rate: 0.118,
    plate_appearances_per_rbi: 11.333,
    plate_appearances_per_home_run: 34.0,
    extra_base_hits: 2,
    stolen_base_average: 0.0,
    strikeout_rate: 0.207,
    ops_string: ".575",
    slg_string: ".310",
    obp_string: ".265",
    avg_string: ".172",
    batting_highlights: "5-29, HR, 3 R, 3 RBI, 2B",
  },
  home_batter_totals: {
    sacrifices: 2,
    at_bats: 33,
    plate_appearances: 38,
    singles: 9,
    doubles: 1,
    triples: 0,
    home_runs: 0,
    sac_flies: 0,
    sac_hits: 2,
    stolen_bases: 1,
    caught_stealing: 0,
    rbi_with_two_outs: 1,
    total_bases: 11,
    runs: 4,
    hits: 10,
    rbi: 4,
    walks: 3,
    strike_outs: 9,
    left_on_base: 11,
    hit_by_pitch: 0,
    ops: 0.675,
    avg: 0.303,
    obp: 0.342,
    slg: 0.333,
    at_bats_per_home_run: 0.0,
    at_bats_per_rbi: 8.25,
    walk_rate: 0.079,
    plate_appearances_per_rbi: 9.5,
    plate_appearances_per_home_run: 0.0,
    extra_base_hits: 1,
    stolen_base_average: 1.0,
    strikeout_rate: 0.273,
    ops_string: ".675",
    slg_string: ".333",
    obp_string: ".342",
    avg_string: ".303",
    batting_highlights: "10-33, 4 R, 4 RBI, 2B, SB",
  },
};
export default function MLB() {
  const [home, setHome] = useState({
    team_info: stats.home_team,
    scores: stats.home_period_scores,
    errors: stats.home_errors,
    batters: stats.home_batters,
    pitchers: stats.home_pitchers,
    fielding: stats.home_fielding,
    batter_totals: stats.home_batter_totals,
  });
  const [away, setAway] = useState({
    team_info: stats.away_team,
    scores: stats.away_period_scores,
    errors: stats.away_errors,
    batters: stats.away_batters,
    pitchers: stats.away_pitchers,
    fielding: stats.away_fielding,
    batter_totals: stats.away_batter_totals,
  });

  const size = useContext(ResponsiveContext);
  return (
    <Box gap="medium">
      <TeamBox
        away={{
          team_info: away.team_info,
          score: away.scores.reduce((a, b) => a + b, 0),
        }}
        home={{
          team_info: home.team_info,
          score: home.scores.reduce((a, b) => a + b, 0),
        }}
        status={stats.event_information.status}
      />
      <BoxScore home={home} away={away} />
      <Box
        direction={size === "small" ? "column" : "row"}
        gap="medium"
        align="start"
        justify="center"
        height="600px"
      >
        <HittingCard
          batters={away.batters}
          team={away.team_info.abbreviation}
          totals={away.batter_totals}
        />
        <HittingCard
          batters={home.batters}
          team={home.team_info.abbreviation}
          totals={home.batter_totals}
        />
      </Box>
      <Box
        direction={size === "small" ? "column" : "row"}
        gap="medium"
        align="start"
        justify="center"
      >
        <PitchingCard
          pitchers={away.pitchers}
          team={away.team_info.abbreviation}
        />
        <PitchingCard
          pitchers={home.pitchers}
          team={home.team_info.abbreviation}
        />
      </Box>
      <Box height="small" />
    </Box>
  );
}
